vim.g.mapleader = ","
require('user.plugins')
require('user.options')
require('user.colorscheme')
require('user.whichkey')
require('user.treesitter')
require('user.registers')
require('user.completion')
require('user.lsp_installer')
require('user.keymaps')
