vim.g.mapleader = ","
require('therushingan.plugins')
require('therushingan.options')
require('therushingan.colorscheme')
require('therushingan.whichkey')
require('therushingan.treesitter')
require('therushingan.registers')
require('therushingan.completion')
-- require('therushingan.lsp_installer')
require('therushingan.keymaps')
